import Head from "next/head"
import { colors } from "styles/theme"
import AppLayout from "components/AppLayout"
import { loginWithGitHub, onAuthStateChanged } from "firebase/client"
import Button from "components/Button"
import { useState, useEffect } from "react"
import Avatar from "components/Avatar"

export default function Home() {
  const [user, setUser] = useState(undefined)
  useEffect(() => {
    onAuthStateChanged(setUser)
  }, [])
  const handleClick = () => {
    loginWithGitHub()
      .then(setUser)
      .catch((err) => {
        console.log(err)
      })
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
        <section>
          <img src="/im.png" width="100" />

          <h1>Tweetet</h1>
          <h2>
            Talk about development
            <br />
            with developers 👨‍💻
          </h2>
          <div>
            {user === null && (
              <Button onClick={handleClick}>Login with GitHub</Button>
            )}
            {user && user.avatar && (
              <div>
                <Avatar
                  alt={user.username}
                  src={user.avatar}
                  text={user.username}
                />

                <h5>Mariantonieta Chacon</h5>
              </div>
            )}
          </div>
        </section>
      </AppLayout>

      <style jsx>{`
        div {
          margin-top: 16px;
        }
        h5 {
          margin-top: -35px;
          margin-left: 60px;
        }
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
        h1 {
          color: ${colors.secondary};
          font-weight: 800;
          margin-bottom: 16px;
        }
        h2 {
          color: ${colors.primary};
          font-size: 21px;
          margin: 0;
        }
      `}</style>
    </div>
  )
}
