import Head from 'next/head'
import { colors } from '../styles/theme'
import AppLayout from '../components/AppLayout'
import Button from  '../components/Button'
export default function Home() {
  return (
    <div>
     <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout>
      <section>

      <img src="/im.png" width="100"/>
       
        <h1>Tweetet</h1>
        <h2>Talk about development<br />with developers 👨‍💻</h2>
       <Button>Login with GitHub</Button>
       </section>
        </AppLayout>

        <style jsx>{`
        div {
          margin-top: 16px;
        }
        section {
          display: grid;
          height: 100%;
          place-content: center;
          place-items: center;
        }
        h1 {
          color: ${colors.secondary};
          font-weight: 800;
          margin-bottom: 16px;
        }
        h2 {
          color: ${colors.primary};
          font-size: 21px;
          margin: 0;
        }
        `}</style>
    </div>
  )
}
